defmodule LiveElementsTest do
  use ExUnit.Case, async: true

  alias LiveDebugger.LiveElements

  setup do
    # This state was generated by using `:sys.get_state()` on PoC of LiveDebugger
    [
      state: %{
        socket: %{
          id: "phx-live-view-id",
          view: DbgPocWeb.Root,
          assigns: %{
            name: "David",
            socket_id: "phx-socket-id"
          }
        },
        components:
          {%{
             1 =>
               {DbgPocWeb.LiveComponents.First, "live_first",
                %{
                  name: "David",
                  myself: %Phoenix.LiveComponent.CID{cid: 1}
                },
                %{
                  children_cids: [4, 3]
                },
                {3_282_018_742_958_242_513_850_596_067_786_202_504,
                 %{
                   0 =>
                     {95_551_922_260_049_747_650_004_487_942_996_607_201,
                      %{3 => {260_881_389_306_357_638_738_530_585_973_715_200_892, %{}}}}
                 }}},
             2 =>
               {DbgPocWeb.LiveComponents.Second, "live_second",
                %{
                  id: "live_second",
                  myself: %Phoenix.LiveComponent.CID{cid: 2}
                },
                %{
                  children_cids: []
                },
                {287_874_446_486_699_803_129_448_444_516_152_742_112,
                 %{
                   0 =>
                     {95_551_922_260_049_747_650_004_487_942_996_607_201,
                      %{3 => {13_257_739_890_174_628_906_503_265_180_604_871_217, %{}}}}
                 }}},
             3 =>
               {DbgPocWeb.LiveComponents.Second, "live_third",
                %{
                  id: "live_third",
                  myself: %Phoenix.LiveComponent.CID{cid: 3}
                },
                %{
                  children_cids: []
                },
                {287_874_446_486_699_803_129_448_444_516_152_742_112,
                 %{
                   0 =>
                     {95_551_922_260_049_747_650_004_487_942_996_607_201,
                      %{3 => {13_257_739_890_174_628_906_503_265_180_604_871_217, %{}}}}
                 }}},
             4 =>
               {DbgPocWeb.LiveComponents.Second, "live_fourth",
                %{
                  id: "live_fourth",
                  myself: %Phoenix.LiveComponent.CID{cid: 4}
                },
                %{
                  children_cids: [5]
                },
                {287_874_446_486_699_803_129_448_444_516_152_742_112,
                 %{
                   0 =>
                     {95_551_922_260_049_747_650_004_487_942_996_607_201,
                      %{
                        3 =>
                          {13_257_739_890_174_628_906_503_265_180_604_871_217,
                           %{1 => {261_574_305_315_477_219_693_617_515_797_488_047_083, %{}}}}
                      }}
                 }}},
             5 =>
               {DbgPocWeb.LiveComponents.Second, "live_fifth",
                %{
                  id: "live_fifth",
                  myself: %Phoenix.LiveComponent.CID{cid: 5}
                },
                %{
                  children_cids: []
                },
                {287_874_446_486_699_803_129_448_444_516_152_742_112,
                 %{
                   0 =>
                     {95_551_922_260_049_747_650_004_487_942_996_607_201,
                      %{3 => {13_257_739_890_174_628_906_503_265_180_604_871_217, %{}}}}
                 }}}
           },
           %{
             DbgPocWeb.LiveComponents.First => %{"live_first" => 1},
             DbgPocWeb.LiveComponents.Second => %{
               "live_third" => 3,
               "live_second" => 2,
               "live_fourth" => 4,
               "live_fith" => 5
             }
           }, 6}
      }
    ]
  end

  test "live_elements returns live view and list of elements", ctx do
    assert {:ok, {root, live_elements}} = LiveElements.live_elements(ctx[:state])
    assert %LiveElements.View{} = root
    assert length(live_elements) == 5
  end

  test "build_tree creates tree of components", ctx do
    assert {:ok,
            %LiveElements.View{
              id: "phx-live-view-id",
              children: [
                %LiveElements.Component{
                  id: "live_first",
                  children: [
                    %LiveElements.Component{
                      id: "live_third",
                      children: []
                    },
                    %LiveElements.Component{
                      id: "live_fourth",
                      children: [
                        %LiveElements.Component{
                          id: "live_fifth",
                          children: []
                        }
                      ]
                    }
                  ]
                },
                %LiveElements.Component{
                  id: "live_second",
                  children: []
                }
              ]
            }} = LiveElements.build_tree(ctx[:state])
  end
end
