defmodule LiveElementsTest do
  use ExUnit.Case, async: true

  alias LiveDebugger.LiveElements


  setup do
    # This state was generated by using `:sys.get_state()` on PoC of LiveDebugger
    [state: %{
      socket: %{
        id: "phx-GA_XeAqyAGXDuQFj",
        endpoint: DbgPocWeb.Endpoint,
        view: DbgPocWeb.Root,
        parent_pid: nil,
        router: DbgPocWeb.Router,
        assigns: %{
          name: "David",
          pid: "<0.605.0>",
          counter: 0,
          __changed__: %{},
          live_debug: %{socket_id: "phx-GA_XeAqyAGXDuQFj"},
          socket_id: "phx-GA_XeAqyAGXDuQFj",
          live_action: nil,
          datetime: nil
        }
      },
      components: {%{
         1 => {DbgPocWeb.LiveComponents.First, "live_first",
          %{
            name: "David",
            __changed__: %{},
            flash: %{},
            myself: %Phoenix.LiveComponent.CID{cid: 1}
          },
          %{
            lifecycle: %Phoenix.LiveView.Lifecycle{
              after_render: [],
              handle_async: [],
              handle_event: [],
              handle_info: [],
              handle_params: [],
              mount: []
            },
            live_temp: %{},
            root_view: DbgPocWeb.Root,
            children_cids: [4, 3]
          },
          {3282018742958242513850596067786202504,
           %{
             0 => {95551922260049747650004487942996607201,
              %{3 => {260881389306357638738530585973715200892, %{}}}}
           }}},
         2 => {DbgPocWeb.LiveComponents.Second, "live_secondTT",
          %{
            id: "live_secondTT",
            __changed__: %{},
            flash: %{},
            myself: %Phoenix.LiveComponent.CID{cid: 2}
          },
          %{
            lifecycle: %Phoenix.LiveView.Lifecycle{
              after_render: [],
              handle_async: [],
              handle_event: [],
              handle_info: [],
              handle_params: [],
              mount: []
            },
            live_temp: %{},
            root_view: DbgPocWeb.Root,
            children_cids: []
          },
          {287874446486699803129448444516152742112,
           %{
             0 => {95551922260049747650004487942996607201,
              %{3 => {13257739890174628906503265180604871217, %{}}}}
           }}},
         3 => {DbgPocWeb.LiveComponents.Second, "live_second",
          %{
            id: "live_second",
            __changed__: %{},
            flash: %{},
            myself: %Phoenix.LiveComponent.CID{cid: 3}
          },
          %{
            lifecycle: %Phoenix.LiveView.Lifecycle{
              after_render: [],
              handle_async: [],
              handle_event: [],
              handle_info: [],
              handle_params: [],
              mount: []
            },
            live_temp: %{},
            root_view: DbgPocWeb.Root,
            children_cids: []
          },
          {287874446486699803129448444516152742112,
           %{
             0 => {95551922260049747650004487942996607201,
              %{3 => {13257739890174628906503265180604871217, %{}}}}
           }}},
         4 => {DbgPocWeb.LiveComponents.Second, "live_secondTTT",
          %{
            id: "live_secondTTT",
            __changed__: %{},
            inner_block: [
              %{
                __slot__: :inner_block,
                inner_block: nil
              }
            ],
            flash: %{},
            myself: %Phoenix.LiveComponent.CID{cid: 4}
          },
          %{
            lifecycle: %Phoenix.LiveView.Lifecycle{
              after_render: [],
              handle_async: [],
              handle_event: [],
              handle_info: [],
              handle_params: [],
              mount: []
            },
            live_temp: %{},
            root_view: DbgPocWeb.Root,
            children_cids: [5]
          },
          {287874446486699803129448444516152742112,
           %{
             0 => {95551922260049747650004487942996607201,
              %{
                3 => {13257739890174628906503265180604871217,
                 %{1 => {261574305315477219693617515797488047083, %{}}}}
              }}
           }}},
         5 => {DbgPocWeb.LiveComponents.Second, "live_secondTTTT",
          %{
            id: "live_secondTTTT",
            __changed__: %{},
            flash: %{},
            myself: %Phoenix.LiveComponent.CID{cid: 5}
          },
          %{
            lifecycle: %Phoenix.LiveView.Lifecycle{
              after_render: [],
              handle_async: [],
              handle_event: [],
              handle_info: [],
              handle_params: [],
              mount: []
            },
            live_temp: %{},
            root_view: DbgPocWeb.Root,
            children_cids: []
          },
          {287874446486699803129448444516152742112,
           %{
             0 => {95551922260049747650004487942996607201,
              %{3 => {13257739890174628906503265180604871217, %{}}}}
           }}}
       },
       %{
         DbgPocWeb.LiveComponents.First => %{"live_first" => 1},
         DbgPocWeb.LiveComponents.Second => %{
           "live_second" => 3,
           "live_secondTT" => 2,
           "live_secondTTT" => 4,
           "live_secondTTTT" => 5
         }
       }, 6},
    }]
  end

  test "live_elements returns live view and list of elements", ctx do
    assert {:ok, {root, live_elements}} = LiveElements.live_elements(ctx[:state])
    assert %LiveElements.View{} = root
    assert length(live_elements) == 5
  end

  test "build_tree creates tree of components", ctx do
    assert {:ok, _} = LiveElements.build_tree(ctx[:state])
  end
end
