name: Feature request
about: Suggest an idea for this project
title: "[FEATURE] Some new feature"
labels: enhancement
assignees: ""

body:
  - type: markdown
    attributes:
      value: |
        ### Is your feature request related to a problem? Please describe.
        <!-- 
        Add a clear and concise description of what the problem is. Ex.` I'm always frustrated when [...]`.
        Please add example on how to use this feature/when it will come in handy.
        -->

        ### Describe the solution you'd like
        <!-- 
        Provide solution on the problem as clear and concise as possible 
        -->

        ### Describe alternatives you've considered
        <!--
        Have you considered any alternative solutions or features? If so, please provide a clear and concise description of any alternative solutions or features you've considered. This can help us understand your thought process and assess other potential ways to solve the same issue.
        -->


        ### Additional context
        <!-- 
        Add any other context or screenshots about the feature request here. 
        -->

  - type: dropdown
    id: type
    attributes:
      label: Type
      description: What type of issue is this?
      options:
        - Feature
        - Bug
        - Documentation
    validations:
      required: true

project:
  - name: LiveDebugger
