defmodule LiveDebugger.Structs.Trace do
  @moduledoc """
  This module provides a module to represent a trace.
  Currently LiveDebugger supports two types of traces:
  - FunctionTrace - represents a function call trace (usually call of LiveView/LiveComponent callback).
  - DiffTrace - represents a diff trace (HTML diff generated by LiveView/LiveComponent sent to the client).

  Each trace has:
  - id - unique id of the trace which is generated by :dbg tracer.
  - pid - pid of the LiveView that generated the trace.
  - timestamp - timestamp of the trace.
  """

  alias LiveDebugger.Structs.Trace.FunctionTrace
  alias LiveDebugger.Structs.Trace.DiffTrace

  @type t() :: FunctionTrace.t() | DiffTrace.t()

  @type id() :: neg_integer() | 0

  defguard is_trace(trace) when is_struct(trace, FunctionTrace) or is_struct(trace, DiffTrace)
  defguard is_trace_id(trace_id) when is_integer(trace_id) and trace_id <= 0
end
