# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Backward Compatibility CI

on:
  push:
    branches:
      - main
      - "v*.*"
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1.20.4
        with:
          elixir-version: "1.16.0" # [Required] Define the Elixir version
          otp-version: "26.0.2" # [Required] Define the Erlang/OTP version

      - name: Copy mix.lock
        run: cp ./.github/workflows/assets/mix.lock mix.lock

      - name: Cache Mix
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: backward-compatibility-${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: backward-compatibility-${{ runner.os }}-mix-

      - name: Install Dependencies
        run: mix deps.get

      - name: Compile project
        run: mix compile --warnings-as-errors

      - name: Run unit tests
        run: mix test

      - name: Run e2e tests
        run: mix e2e
