name: Publish to Hex.pm

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish package to Hex.pm
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Elixir
        uses: erlef/setup-beam@v1.18.0
        with:
          elixir-version: "1.17.3"
          otp-version: "27.1.2"

      - name: Cache Mix
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Install Dependencies
        run: mix deps.get

      - name: Publish to Hex.pm
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        run: |
          mix hex.build
          mix hex.publish --yes
